apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx  
    spec:
      containers:
      - name: nginx-test
        image: nginx:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
